"""m30_perf_indexes

Revision ID: 0848a1f0aa35
Revises: i7d8e9f0a1b2
Create Date: 2026-09-08 07:35:11.834722
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0848a1f0aa35'
down_revision: Union[str, None] = 'i7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.create_index('ix_bill_items_bill_type', ['bill_id', 'type'], unique=False)

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index('ix_bills_tenant_booking_status', ['tenant_id', 'booking_id', 'status'], unique=False)
        batch_op.create_index('ix_bills_tenant_hotel_status', ['tenant_id', 'hotel_id', 'status'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('ix_bookings_hotel_room_status', ['hotel_id', 'room_no', 'status'], unique=False)
        batch_op.create_index('ix_bookings_tenant_hotel_checkin', ['tenant_id', 'hotel_id', 'check_in_date'], unique=False)
        batch_op.create_index('ix_bookings_tenant_room_id', ['tenant_id', 'room_no', 'id'], unique=False)
        batch_op.create_index('ix_bookings_tenant_status_room', ['tenant_id', 'status', 'room_no'], unique=False)

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.create_index('ix_guests_tenant_idno', ['tenant_id', 'id_no'], unique=False)

    with op.batch_alter_table('housekeeping_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_hk_tenant_hotel_status', ['tenant_id', 'hotel_id', 'status'], unique=False)

    with op.batch_alter_table('pos_orders', schema=None) as batch_op:
        batch_op.create_index('ix_pos_orders_tenant_hotel_status_created', ['tenant_id', 'hotel_id', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index('ix_rooms_tenant_hotel_state', ['tenant_id', 'hotel_id', 'state'], unique=False)
        batch_op.create_index('ix_rooms_tenant_type', ['tenant_id', 'room_type_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index('ix_rooms_tenant_type')
        batch_op.drop_index('ix_rooms_tenant_hotel_state')

    with op.batch_alter_table('pos_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_pos_orders_tenant_hotel_status_created')

    with op.batch_alter_table('housekeeping_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_hk_tenant_hotel_status')

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_index('ix_guests_tenant_idno')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_bookings_tenant_status_room')
        batch_op.drop_index('ix_bookings_tenant_room_id')
        batch_op.drop_index('ix_bookings_tenant_hotel_checkin')
        batch_op.drop_index('ix_bookings_hotel_room_status')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index('ix_bills_tenant_hotel_status')
        batch_op.drop_index('ix_bills_tenant_booking_status')

    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.drop_index('ix_bill_items_bill_type')

    # ### end Alembic commands ###
