"""notification_recipients_and_subscriptions

Revision ID: 271462418bcd
Revises: ae16e2cfc5a2
Create Date: 2026-09-04 13:53:43.476355
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '271462418bcd'
down_revision: Union[str, None] = 'ae16e2cfc5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_subscriptions',
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ref_type', name='uq_sub_tenant_ref')
    )
    with op.batch_alter_table('notification_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_subscriptions_ref_type'), ['ref_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_subscriptions_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        # 既有行 NOT NULL 加列需 server_default，否则 SQLite 拒绝；'[]' 由 JSON 类型反序列化为空列表
        batch_op.add_column(sa.Column('recipients', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('recipients')

    with op.batch_alter_table('notification_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_subscriptions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notification_subscriptions_ref_type'))

    op.drop_table('notification_subscriptions')
    # ### end Alembic commands ###
