"""baseline full schema at Sprint 15

Revision ID: 69a582a7c5cc
Revises: 
Create Date: 2026-09-04 00:10:45.154786
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69a582a7c5cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('guest_name', sa.String(length=64), nullable=True),
    sa.Column('guest_phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('handoff_reason', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('commission_rules',
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('rate_bps', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel')
    )
    with op.batch_alter_table('commission_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_rules_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('hotels',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotels_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('login_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_sessions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_sessions_token'), ['token'], unique=True)

    op.create_table('openapi_apps',
    sa.Column('app_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('callback_url', sa.String(length=512), nullable=True),
    sa.Column('events_subscribed', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('openapi_apps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openapi_apps_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pay_notifies',
    sa.Column('out_trade_no', sa.String(length=40), nullable=False),
    sa.Column('notify_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'notify_id')
    )
    with op.batch_alter_table('pay_notifies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pay_notifies_out_trade_no'), ['out_trade_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_notifies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pricing_rules',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('high_occ_threshold', sa.Integer(), nullable=False),
    sa.Column('low_occ_threshold', sa.Integer(), nullable=False),
    sa.Column('max_uplift_bps', sa.Integer(), nullable=False),
    sa.Column('max_discount_bps', sa.Integer(), nullable=False),
    sa.Column('weekend_uplift_bps', sa.Integer(), nullable=False),
    sa.Column('competitor_strategy', sa.String(length=16), nullable=False),
    sa.Column('competitor_undercut_bps', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('report_templates',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('dimensions', sa.Text(), nullable=False),
    sa.Column('metrics', sa.Text(), nullable=False),
    sa.Column('filters', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_templates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('hotel_scoped', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('room_types',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_types_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenants',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_chain', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('salt', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_user_tenant_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('alert_notifications',
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('suggested_action', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_notifications_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_notifications_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_notifications_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('approval_tickets',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('applicant', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approver', sa.String(length=64), nullable=True),
    sa.Column('decision_note', sa.String(length=256), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_tickets_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_tickets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('business_days',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('audited_at', sa.String(length=40), nullable=True),
    sa.Column('audited_by', sa.String(length=64), nullable=True),
    sa.Column('suspended_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'business_date')
    )
    with op.batch_alter_table('business_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_days_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_days_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('commission_reconciliations',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('room_revenue_cents', sa.Integer(), nullable=False),
    sa.Column('commission_rate_bps', sa.Integer(), nullable=False),
    sa.Column('commission_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reconciled_at', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'business_date', 'channel')
    )
    with op.batch_alter_table('commission_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_reconciliations_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_reconciliations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('daily_reports',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('arrived_rooms', sa.Integer(), nullable=False),
    sa.Column('departed_rooms', sa.Integer(), nullable=False),
    sa.Column('occupied_rooms', sa.Integer(), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('room_revenue', sa.Integer(), nullable=False),
    sa.Column('other_revenue', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Integer(), nullable=False),
    sa.Column('adr', sa.Integer(), nullable=False),
    sa.Column('occ_pct', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reports_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reports_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('group_price_policies',
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('price_floor_cents', sa.Integer(), nullable=False),
    sa.Column('price_ceiling_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issued_by', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_price_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_price_policies_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_price_policies_room_type_id'), ['room_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_price_policies_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_price_policies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('housekeeping_tasks',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_no', sa.String(length=16), nullable=False),
    sa.Column('task_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assignee', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('housekeeping_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_housekeeping_tasks_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_housekeeping_tasks_room_no'), ['room_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_housekeeping_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_housekeeping_tasks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('members',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('stored_value', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('stays', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'phone')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('metric_snapshots',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('metric_type', sa.String(length=32), nullable=False),
    sa.Column('dimension', sa.String(length=64), nullable=True),
    sa.Column('metric_name', sa.String(length=32), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_snapshots_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_snapshots_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_snapshots_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('notifications',
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.String(length=512), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('openapi_keys',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_mask', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revoked_at', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['openapi_apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('openapi_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openapi_keys_key_hash'), ['key_hash'], unique=False)

    op.create_table('openapi_webhook_subscriptions',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('endpoint_url', sa.String(length=512), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['openapi_apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('openapi_webhook_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openapi_webhook_subscriptions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('price_calendar',
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'room_type_id', 'date')
    )
    with op.batch_alter_table('price_calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_calendar_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_calendar_room_type_id'), ['room_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_calendar_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('price_recommendations',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('base_price_cents', sa.Integer(), nullable=False),
    sa.Column('recommended_price_cents', sa.Integer(), nullable=False),
    sa.Column('adjustment_bps', sa.Integer(), nullable=False),
    sa.Column('demand_index', sa.Integer(), nullable=False),
    sa.Column('sample_days', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['pricing_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_recommendations_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_recommendations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('rate_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('member_level', sa.String(length=16), nullable=False),
    sa.Column('agreement_type', sa.String(length=16), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('stay_type', sa.String(length=16), nullable=False),
    sa.Column('discount_pct', sa.Integer(), nullable=False),
    sa.Column('restrictions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    with op.batch_alter_table('rate_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_codes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('rooms',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('room_no', sa.String(length=16), nullable=False),
    sa.Column('floor', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'room_no')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('shift_handovers',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('cashier', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opening_float_cents', sa.Integer(), nullable=False),
    sa.Column('expected_cash_cents', sa.Integer(), nullable=False),
    sa.Column('counted_cash_cents', sa.Integer(), nullable=False),
    sa.Column('discrepancy_cents', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.String(length=40), nullable=True),
    sa.Column('closed_at', sa.String(length=40), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_handovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_handovers_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_handovers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('wake_up_calls',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_no', sa.String(length=16), nullable=False),
    sa.Column('guest_name', sa.String(length=64), nullable=False),
    sa.Column('call_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wake_up_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wake_up_calls_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wake_up_calls_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bookings',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('rate_code_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('guest_name', sa.String(length=64), nullable=False),
    sa.Column('guest_phone', sa.String(length=32), nullable=True),
    sa.Column('id_doc_no', sa.String(length=64), nullable=True),
    sa.Column('check_in_date', sa.String(length=10), nullable=False),
    sa.Column('check_out_date', sa.String(length=10), nullable=False),
    sa.Column('room_no', sa.String(length=16), nullable=True),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['rate_code_id'], ['rate_codes.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_chat_session_id'), ['chat_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_room_type_id'), ['room_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('openapi_webhook_deliveries',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('event_topic', sa.String(length=128), nullable=False),
    sa.Column('event_payload', sa.String(length=4096), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.String(length=2048), nullable=True),
    sa.Column('attempted_at', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['openapi_webhook_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_state_events',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_no', sa.String(length=16), nullable=False),
    sa.Column('from_state', sa.String(length=24), nullable=False),
    sa.Column('to_state', sa.String(length=24), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_state_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_state_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_state_events_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_state_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bills',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('bill_no', sa.String(length=32), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=64), nullable=False),
    sa.Column('room_no', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'bill_no')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bills_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('psb_upload_tasks',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=64), nullable=False),
    sa.Column('id_doc_no', sa.String(length=64), nullable=True),
    sa.Column('room_no', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psb_upload_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psb_upload_tasks_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_psb_upload_tasks_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_psb_upload_tasks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('adjustment_vouchers',
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('business_day_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['business_day_id'], ['business_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adjustment_vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adjustment_vouchers_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adjustment_vouchers_business_day_id'), ['business_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adjustment_vouchers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bill_items',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_items_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pay_orders',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('out_trade_no', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('prepay_id', sa.String(length=64), nullable=True),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'out_trade_no')
    )
    with op.batch_alter_table('pay_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pay_orders_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_orders_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_orders_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_orders_out_trade_no'), ['out_trade_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_orders_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('payments',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('is_deposit', sa.Boolean(), nullable=False),
    sa.Column('ref_no', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payments_bill_id'))

    op.drop_table('payments')
    with op.batch_alter_table('pay_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pay_orders_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pay_orders_status'))
        batch_op.drop_index(batch_op.f('ix_pay_orders_out_trade_no'))
        batch_op.drop_index(batch_op.f('ix_pay_orders_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_pay_orders_booking_id'))
        batch_op.drop_index(batch_op.f('ix_pay_orders_bill_id'))

    op.drop_table('pay_orders')
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bill_items_bill_id'))

    op.drop_table('bill_items')
    with op.batch_alter_table('adjustment_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adjustment_vouchers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_adjustment_vouchers_business_day_id'))
        batch_op.drop_index(batch_op.f('ix_adjustment_vouchers_bill_id'))

    op.drop_table('adjustment_vouchers')
    with op.batch_alter_table('psb_upload_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psb_upload_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_psb_upload_tasks_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_psb_upload_tasks_booking_id'))

    op.drop_table('psb_upload_tasks')
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bills_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_bills_booking_id'))

    op.drop_table('bills')
    with op.batch_alter_table('room_state_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_state_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_room_state_events_room_id'))
        batch_op.drop_index(batch_op.f('ix_room_state_events_occurred_at'))

    op.drop_table('room_state_events')
    op.drop_table('openapi_webhook_deliveries')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_room_type_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_chat_session_id'))

    op.drop_table('bookings')
    with op.batch_alter_table('wake_up_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wake_up_calls_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_wake_up_calls_hotel_id'))

    op.drop_table('wake_up_calls')
    with op.batch_alter_table('shift_handovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_handovers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_shift_handovers_hotel_id'))

    op.drop_table('shift_handovers')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_state'))
        batch_op.drop_index(batch_op.f('ix_rooms_hotel_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('rate_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_codes_tenant_id'))

    op.drop_table('rate_codes')
    with op.batch_alter_table('price_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_recommendations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_price_recommendations_hotel_id'))

    op.drop_table('price_recommendations')
    with op.batch_alter_table('price_calendar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_calendar_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_price_calendar_room_type_id'))
        batch_op.drop_index(batch_op.f('ix_price_calendar_date'))

    op.drop_table('price_calendar')
    with op.batch_alter_table('openapi_webhook_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openapi_webhook_subscriptions_tenant_id'))

    op.drop_table('openapi_webhook_subscriptions')
    with op.batch_alter_table('openapi_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openapi_keys_key_hash'))

    op.drop_table('openapi_keys')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_hotel_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_business_date'))

    op.drop_table('metric_snapshots')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_members_hotel_id'))

    op.drop_table('members')
    with op.batch_alter_table('housekeeping_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_housekeeping_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_housekeeping_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_housekeeping_tasks_room_no'))
        batch_op.drop_index(batch_op.f('ix_housekeeping_tasks_hotel_id'))

    op.drop_table('housekeeping_tasks')
    with op.batch_alter_table('group_price_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_price_policies_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_group_price_policies_status'))
        batch_op.drop_index(batch_op.f('ix_group_price_policies_room_type_id'))
        batch_op.drop_index(batch_op.f('ix_group_price_policies_hotel_id'))

    op.drop_table('group_price_policies')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_daily_reports_hotel_id'))

    op.drop_table('daily_reports')
    with op.batch_alter_table('commission_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_reconciliations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_commission_reconciliations_hotel_id'))

    op.drop_table('commission_reconciliations')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('business_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_days_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_business_days_hotel_id'))

    op.drop_table('business_days')
    with op.batch_alter_table('approval_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_tickets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_approval_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_approval_tickets_hotel_id'))

    op.drop_table('approval_tickets')
    with op.batch_alter_table('alert_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_notifications_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_alert_notifications_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_alert_notifications_alert_type'))

    op.drop_table('alert_notifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))

    op.drop_table('users')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_tenant_id'))

    op.drop_table('user_roles')
    op.drop_table('tenants')
    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_types_tenant_id'))

    op.drop_table('room_types')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_tenant_id'))

    op.drop_table('roles')
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_templates_tenant_id'))

    op.drop_table('report_templates')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_tenant_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('pricing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_rules_tenant_id'))

    op.drop_table('pricing_rules')
    with op.batch_alter_table('pay_notifies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pay_notifies_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pay_notifies_out_trade_no'))

    op.drop_table('pay_notifies')
    with op.batch_alter_table('openapi_apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openapi_apps_tenant_id'))

    op.drop_table('openapi_apps')
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_sessions_token'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_tenant_id'))

    op.drop_table('login_sessions')
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotels_tenant_id'))

    op.drop_table('hotels')
    with op.batch_alter_table('commission_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_rules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_commission_rules_channel'))

    op.drop_table('commission_rules')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_tenant_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
