"""notification_level_muted_and_preferences

Revision ID: ae16e2cfc5a2
Revises: a4c58ae1396f
Create Date: 2026-09-04 13:36:47.591645
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ae16e2cfc5a2'
down_revision: Union[str, None] = 'a4c58ae1396f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('dnd_enabled', sa.Boolean(), nullable=False),
    sa.Column('dnd_start', sa.String(length=5), nullable=False),
    sa.Column('dnd_end', sa.String(length=5), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=16), nullable=False, server_default='normal'))
        batch_op.add_column(sa.Column('muted', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_notifications_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_muted'), ['muted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_muted'))
        batch_op.drop_index(batch_op.f('ix_notifications_level'))
        batch_op.drop_column('muted')
        batch_op.drop_column('level')

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_tenant_id'))

    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
